### PR TITLE
Fix: js dependency bump

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by de-code** [comment]
Thank you for looking into this.

I upgraded `webpack-cli`. It is getting further but still failing.

**Comment by de-code** [comment]
it should pass ci now but at least locally isn't actually working yet.

**Comment by de-code** [comment]
It breaks with: https://github.com/zilverline/react-tap-event-plugin/issues/121

**Comment by lsh-0** [comment]
nice catch

**Comment by de-code** [comment]
There are currently no end-to-end tests for the client. Therefore I would always sanity check any client library upgrades.

(There are end-to-end tests for the ETL though and smoke test for the Python server)

**Comment by de-code** [comment]
The client seems to be superficially working now. I somehow wiped my local data volume. I am running the ETL again to check it with actual data. This might take a while though.

**Comment by de-code** [comment]
Actually the ETL fails due to: https://github.com/elifesciences/issues/issues/5079 (which also failed in ci)

**Comment by de-code** [comment]
No update yet, I think I will focus on it after next Wed when I may do some other work on PeerScout. (https://github.com/elifesciences/issues/issues/5079 should be fixed first)

**Comment by lsh-0** [comment]
Thank you for the update, @de-code , we get bugged daily about it from github

**Comment by de-code** [comment]
Almost surprisingly this actually still worked.

**Pull request merged**
